---
- name: Get hostname
  hosts: k3s
  become: true
  become_user: root

  tasks:
  - name: Get hostname
    ansible.builtin.hostname:
      name: "{{ ansible_hostname }}"
    register: hostname

  - name: Print hostname
    debug:
      var: hostname
