---
- name: Install Open VM Tools package
  hosts: all
  become: yes
  tasks:
    - name: Update the repository cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Open VM Tools package
      ansible.builtin.apt:
        name: open-vm-tools
        state: present
