- name: Update & Upgrade apt packages
  hosts: all
  become: true
  tasks:
    - name: Apt Update and upgrade
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 # Update the cache if it's older than 1 day